### ISSUE TITLE
UIScrollview+DelegateBlocks not working for me.

### ISSUE THREAD

**Issue by nlabhart** [c-rack/protocolblocks#2]
I am using your UIScrollview+DelegateBlocks class in my project. I drug these files only into my Xcode project. I am setting the delegate block within a public class method (static, +). The scrollView was created on the Storyboard, and is linked via IBOutlet. See the bottom for the specific block code.  What am I missing here?

+ (id) tutorials:(TutorialSet)setChoice
{
    UINib *nib = [UINib nibWithNibName:@"TutorialDialog" bundle:nil];
    NSArray *nibArray = [nib instantiateWithOwner:self options:nil];
    TutorialsView *me = [nibArray objectAtIndex: 0];
    
    switch (setChoice) {
        case TutorialSetHome:
            me.screens = @[
                           @"12Bar_Homescreen_Tuts-01.png",
                           @"12Bar_Homescreen_Tuts-02.png",
                           @"12Bar_Homescreen_Tuts-03.png",
                           @"12Bar_Homescreen_Tuts-04.png",
                           @"12Bar_Homescreen_Tuts-05.png",
                           @"12Bar_Homescreen_Tuts-06.png"
                         ];
            
            break;
        case TutorialSetCharts:
            me.screens = @[
                          @"12Bar_Charts_Tuts-01.png",
                          @"12Bar_Charts_Tuts-02.png"
                         ];
            break;
        case TutorialSetSets:
            me.screens = @[
                           @"12Bar_Sets_Tuts-01.png"
                           ];
            break;
        case TutorialSetAll:
            me.screens = @[
                           @"12Bar_Homescreen_Tuts-01.png",
                           @"12Bar_Homescreen_Tuts-02.png",
                           @"12Bar_Homescreen_Tuts-03.png",
                           @"12Bar_Homescreen_Tuts-04.png",
                           @"12Bar_Homescreen_Tuts-05.png",
                           @"12Bar_Homescreen_Tuts-06.png",
                           @"12Bar_Charts_Tuts-01.png",
                           @"12Bar_Charts_Tuts-02.png",
                           @"12Bar_Sets_Tuts-01.png"
                           ];
            break;
        default:
            me.screens = @[
                           @"12Bar_Homescreen_Tuts-01.png",
                           @"12Bar_Homescreen_Tuts-02.png",
                           @"12Bar_Homescreen_Tuts-03.png",
                           @"12Bar_Homescreen_Tuts-04.png",
                           @"12Bar_Homescreen_Tuts-05.png",
                           @"12Bar_Homescreen_Tuts-06.png",
                           @"12Bar_Charts_Tuts-01.png",
                           @"12Bar_Charts_Tuts-02.png",
                           @"12Bar_Sets_Tuts-01.png"
                           ];
            break;
    }
    
    [me addTutorialImages:me.screens forScrollView:me.scrollView];
    
    CGRect screenBound = [[UIScreen mainScreen] bounds];
    CGSize screenSize = screenBound.size;
    CGFloat screenWidth = screenSize.width;
    
    me.pageControl = [[UIPageControl alloc] initWithFrame:CGRectMake(0,
                                                                     me.scrollView.frame.origin.y +  me.scrollView.frame.size.height + 20.0,
                                                                     screenWidth,
                                                                     50.0)];
    me.pageControl.numberOfPages = me.screens.count;
    me.pageControl.currentPage = 1;
    [me addSubview:me.pageControl];
    
    [me.scrollView useBlocksForDelegate];
    [me.scrollView onDidScroll:^(UIScrollView *scrollView) {
        CGFloat pageWidth = me.scrollView.frame.size.width;
        float fractionalPage = me.scrollView.contentOffset.x / pageWidth;
        NSInteger page = lround(fractionalPage);
        NSLog(@"page number %f",page);
        me.pageControl.currentPage = page;
    }];
    

    
    return me;
}

**Comment by c-rack** [comment]
@nlabhart Thank you for your issue. I'll try to help you. Could you explain what exactly "does not work"? What is the expected result? What happens instead? Also, could you please reformat your issue so that the source code becomes more readable?

**Comment by nlabhart** [comment]
Sure. The problem is that the block is not firing (NSLog call never gets written to the console). 

Here is the code that is important.

[me.scrollView useBlocksForDelegate];
[me.scrollView onDidScroll:^(UIScrollView *scrollView) {
       CGFloat pageWidth = me.scrollView.frame.size.width;
       float fractionalPage = me.scrollView.contentOffset.x / pageWidth; 
       NSInteger page = lround(fractionalPage);
       NSLog(@"page number %f",page);
       me.pageControl.currentPage = page;
}];

**Comment by c-rack** [comment]
Have you set the delegate properly? For example:
```
scrollView.delegate = self;
```

See also:
https://stackoverflow.com/questions/14095874/scrollviewdidscroll-never-called
https://stackoverflow.com/questions/6842568/uiscrollviewdelegate-not-firing

**Comment by nlabhart** [comment]
Do I need to set the delegate in order to use the blocks?  Guess I didn't
realize that.

I am setting up the UIScrollview from within a UIView, not
UIViewController. This is why I was hoping to use the Blocks setup, because
the UIView cannot adhere to the UIScrollViewDelegate protocol.


Sincerely,

*Noah Labhart*
Partner, Director - GLab, LLC
noah.labhart@glab.mobi
Cell: 817-988-5253

<http://glab.mobi>

**Comment by c-rack** [comment]
> Do I need to set the delegate in order to use the blocks?

Yes.

**Comment by c-rack** [comment]
@nlabhart Has setting the delegate solved your issue?

**Comment by nlabhart** [comment]
No it did not.

I was trying to do this from a UIView, which would not meet the delegate
requirements. I thought that blocks would solve my problem, without having
to reference a parent ViewController as a delegate.

However, if I have to link to a parent controller as a delegate anyway,
might as well implement that method in the view controller.

Thanks for your help though!



Sincerely,

*Noah Labhart*
Partner, Director - GLab, LLC
noah.labhart@glab.mobi
Cell: 817-988-5253

<http://glab.mobi>

**Comment by c-rack** [comment]
OK, sorry for protocolblocks not being the solution you are looking for.
Would you mind to close this issue then?
